# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

# Import keys
eval $(/usr/bin/keychain --eval --agents ssh -Q --quiet ~/.ssh/keys/*.key)
